# Config for server documented here: https://www.dropwizard.io/1.0.2/docs/manual/configuration.html
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: localhost

authorization: # Required for Twitter API authorization (generate here: https://developer.twitter.com/apps)

  consumerAPIKeys:
    apiKey: API_KEY
    apiSecretKey: API_SECRET_KEY

  accessTokenDetails:
    accessToken: ACCESS_TOKEN
    accessTokenSecret: ACCESS_TOKEN_SECRET