host: localhost
port: 8080

consumerKey: WuckCT1FhKvqfFDL3HtXNgImx
consumerSecret: UcUpVGcAzuL31m2Q8aWVr8VQWRVVHJykYmW58GXzbKWQk95ALE
accessToken: 1120754642521088000-uaNrVXOeGTkMlSIzfP9zy8xnMfZYEU
accessTokenSecret: jG3sD0tarW7jMVtWbIBgAKevAxwkCiDqrgwq2LYMaKuZO