# Config for server documented here: https://www.dropwizard.io/1.0.2/docs/manual/configuration.html
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: localhost
  requestLog:
    appenders: []

twitterOAuthCredentials: # Keys and tokens can be generated here: https://developer.twitter.com/apps

  consumerAPIKeys:
    consumerAPIKey: API_KEY
    consumerAPISecretKey: API_SECRET_KEY

  accessTokenDetails:
    accessToken: ACCESS_TOKEN
    accessTokenSecret: ACCESS_TOKEN_SECRET

# Logging config documentation here: https://www.dropwizard.io/0.9.0/docs/manual/configuration.html#logging
# logFormat documentation here: https://logback.qos.ch/manual/layouts.html#conversionWord
logging:
  level: INFO

  appenders:
    - type: console
      timeZone: UTC
      threshold: ALL
      logFormat: "%le  [%d] %m\n"
    - type: file
      currentLogFilename: ./log/startup.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ./log/startup-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%le  [%d] %m\n"

  loggers:
    "requestLogger":
      level: ALL
      additive: false
      appenders:
        - type: console
          timeZone: UTC
          threshold: ALL
          logFormat: "%le  [%d] [TRANSACTION_ID: %X{transID}] %X{remoteIP}:%X{serverPort} - %X{protocol} %X{methodType}
                      %X{requestURI}%X{params} - %m\n"
        - type: file
          currentLogFilename: ./log/requests.log
          threshold: ALL
          archive: true
          archivedLogFilenamePattern: ./log/requests-%d.log.gz
          archivedFileCount: 5
          timeZone: UTC
          logFormat: "%le  [%d] [TRANSACTION_ID: %X{transID}] %X{remoteIP}:%X{serverPort} - %X{protocol} %X{methodType}
                      %X{requestURI}%X{params} - %m\n"