# Config for server documented here: https://www.dropwizard.io/1.0.2/docs/manual/configuration.html
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: localhost
  requestLog:
    appenders: []

twitterOAuthCredentials: # Keys and tokens can be generated here: https://developer.twitter.com/apps

  consumerAPIKey: API_KEY
  consumerAPISecretKey: API_SECRET_KEY

  accessToken: ACCESS_TOKEN
  accessTokenSecret: ACCESS_TOKEN_SECRET

# Logging config documentation here: https://www.dropwizard.io/0.9.0/docs/manual/configuration.html#logging
# logFormat documentation here: https://logback.qos.ch/manual/layouts.html#conversionWord
logging:
  level: DEBUG

  appenders:
    - type: console
      timeZone: UTC
      threshold: ALL
      includeCallerData: true
      logFormat: "%le  [%d] [TRANSACTION_ID: %X{transID}] %X{remoteIP}:%X{serverPort} - \"%X{methodType}
                  %X{requestURI} %X{protocol}\" %X{params}- %class: %m\n"
    - type: file
      currentLogFilename: ./log/tweeting.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ./log/tweeting-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
      includeCallerData: true
      logFormat: "%le  [%d] [TRANSACTION_ID: %X{transID}] %X{remoteIP}:%X{serverPort} - \"%X{methodType}
                  %X{requestURI} %X{protocol}\" %X{params}- %class: %m\n"
