# Config for server documented here: https://www.dropwizard.io/1.0.2/docs/manual/configuration.html
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: localhost
  requestLog:
    appenders: []

twitterOAuthCredentials: # Keys and tokens can be generated here: https://developer.twitter.com/apps

  consumerAPIKeys:
    consumerAPIKey: API_KEY
    consumerAPISecretKey: API_SECRET_KEY

  accessTokenDetails:
    accessToken: ACCESS_TOKEN
    accessTokenSecret: ACCESS_TOKEN_SECRET

# Logging config documentation here: https://www.dropwizard.io/0.9.0/docs/manual/configuration.html#logging
# logFormat documentation here: https://logback.qos.ch/manual/layouts.html#conversionWord
logging:
  level: ALL

  appenders:
    - type: console
      timeZone: UTC
      threshold: INFO
    - type: file
      currentLogFilename: ./log/general.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: ./log/general-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC

  loggers:
    "requestLogger":
      level: ALL
      appenders:
        - type: console
          timeZone: UTC
          threshold: ALL
          includeCallerData: true
          logFormat: "%le  [%d] [TRANSACTION_ID: %X{transID}] %X{remoteIP}:%X{serverPort} - \"%X{methodType}
                      %X{requestURI} %X{protocol}\" %X{params}- %class: %m\n"
        - type: file
          currentLogFilename: ./log/general.log
          threshold: ALL
          archive: true
          archivedLogFilenamePattern: ./log/general-%d.log.gz
          archivedFileCount: 5
          timeZone: UTC
          includeCallerData: true
          logFormat: "%le  [%d] [TRANSACTION_ID: %X{transID}] %X{remoteIP}:%X{serverPort} - \"%X{methodType}
                      %X{requestURI} %X{protocol}\" %X{params}- %class: %m\n"